
export const DEMO_LIST = 'DEMO_LIST'
export const SC_LIST = 'SC_LIST'
export const SC_STAT = 'SC_STAT'
export const SC_DETAIL = 'SC_DETAIL'
export const SC_NOTIFYUSERS = 'SC_NOTIFYUSERS'
export const SC_FAIL = 'SC_FAIL'
export const SC_SAVE = 'SC_SAVE'
export const CL_RELOAD = 'CL_RELOAD'
export const SC_DONE = 'SC_DONE'
